# Generated by Django 5.2.1 on 2025-06-02 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum number of times a user can attempt this quiz. 0 for unlimited.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_mark_percentage',
            field=models.PositiveSmallIntegerField(default=50, help_text='Percentage score required to pass this quiz (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
