# Generated by Django 5.2.1 on 2025-06-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quiz_max_attempts_quiz_pass_mark_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='generation_prompt_params',
            field=models.JSONField(blank=True, help_text='Parameters used for AI quiz generation (e.g., num_questions, types).', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Indicates if this quiz was initially generated by AI.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_text_for_ai',
            field=models.TextField(blank=True, help_text='Source text provided to AI for generating this quiz (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(blank=True, help_text="Link this quiz to a specific lesson (it gates this lesson's completion).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson'),
        ),
    ]
