# Generated by Django 5.2.1 on 2025-06-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_generation_prompt_params_quiz_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer or context for SAQ (shown after attempt or used by AI).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, help_text='Points awarded for a correct answer or max score for this question.'),
        ),
    ]
