# Generated by Django 5.2.1 on 2025-05-27 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('badge_earned', 'Badge Earned'), ('level_up', 'Level Up'), ('new_reply', 'New Forum Reply'), ('thread_activity', 'Forum Thread Activity'), ('quiz_graded', 'Quiz Graded'), ('new_course_recommendation', 'New Course Recommendation'), ('admin_announcement', 'Platform Announcement')], max_length=50)),
                ('message', models.TextField(help_text='The main notification message text.')),
                ('related_course_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('related_thread_slug', models.SlugField(blank=True, max_length=270, null=True)),
                ('related_post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, help_text='A direct URL the user can click to see the relevant content.', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (e.g., replied to a post)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
